name: "Convert issue to PR"

on:
  issues:
    types: [opened, reopened]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Generate random number
        id: random
        run: echo "::set-output name=value::$(echo $RANDOM)"
        shell: bash
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: post-${{ steps.random.outputs.value }}
      - name: setup jq
        uses: dcarbone/install-jq-action@v2
        with:
          version: '${{ inputs.version }}'
          force: '${{ inputs.force }}'
      - name: Append entry
        run: | 
          jq '.[. | length] += { id: "calibre-reader", name: "Calibre reader", author: "test", description: "test", repo: "joethei/obsidian-calibre"}' community-plugins.json > tmp.json
          mv tmp.json community-plugins.json
      - name: commit and push new file
        run: |
          git checkout -b post-${{ steps.random.outputs.value }}
          git config --local user.name "Obsidian Bot"
          git config --local user.email 'admin@obsidian.md'
          git add .
          git commit -m "Add plugin: test"
          git push -u origin post-${{ steps.random.outputs.value }}
        shell: bash
      - name: convert to PR
        run: gh api repos/joethei/obsidian-releases/pulls -f head=post-${{ steps.random.outputs.value }} -f base=main -f "Add plugin" -F issue=${{ github.event.issue.number }}