name: "rebase plugin PR"

on:
  issue_comment:
    types: [created]
    paths:
      - community-plugins.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/rebase')
    steps:
      - name: install jq
        run: sudo apt-get install jq
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "master"
          repository: "joethei/obsidian-releases"
      - name: checkout PR
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: rebase & append
        run: |
          latest_entry=$(jq -r '.[length - 1]' community-plugins.json)
          git rebase -X ours master
          cat community-plugins.json | jq --argjson entry "$latest_entry" '.[length] = $entry' > community-plugins.json
      - name: amend commit & push
        run: |
          git config --local user.name 'Obsidian Bot'
          git config --local user.email 'admin@obsidian.md'
          git add community-plugins.json
          git commit --amend --no-edit
          git push -f origin HEAD:refs/pull/${github.event.issue.number}/head
