name: "rebase on comment"

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/rebase') && github.event.comment.author_association == 'OWNER'
    steps:
      - name: setup jq
        uses: dcarbone/install-jq-action@v2
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.pull_request.base }}"
      - name: process
        run: |
          git config --local user.name "Obsidian Bot"
          git config --local user.email 'admin@obsidian.md'
          git fetch origin
          LAST=$(jq '. | last' community-plugins.json)
          git rebase -X theirs origin/master
          jq '.[. | length] += env.LAST' community-plugins.json > tmp.json
          mv tmp.json community-plugins.json
          git add .
          git commit -m "move to last"
          git push -f
